# Generated by Django 3.2.15 on 2022-08-17 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('email', models.EmailField(max_length=128)),
                ('building', models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=1, null=True)),
                ('floor', models.CharField(blank=True, choices=[('B', 'B'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('R', 'R')], max_length=2, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('description', models.TextField(max_length=512, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('condition', models.CharField(choices=[('New', 'New'), ('Like New', 'Like New'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=20, null=True)),
                ('item_type', models.CharField(choices=[('Clothes', 'Clothes'), ('Kitchen', 'Kitchen'), ('Furniture', 'Furniture'), ('Sporting', 'Sporting'), ('Fitness', 'Fitness'), ('Art', 'Art'), ('Misc', 'Misc')], max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
