# Generated by Django 3.2.15 on 2022-08-16 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thrift', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Like New', 'Like New'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('Clothes', 'Clothes'), ('Kitchen', 'Kitchen'), ('Furniture', 'Furniture'), ('Sporting', 'Sporting'), ('Fitness', 'Fitness')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='building',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='floor',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('R', 'R')], max_length=2, null=True),
        ),
    ]
