# Generated by Django 3.2.15 on 2022-08-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrift', '0004_item_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='buyer',
        ),
        migrations.AlterField(
            model_name='item',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
