# Generated by Django 3.2.15 on 2022-08-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrift', '0005_auto_20220825_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date_sold',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sold',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
