# Generated by Django 3.2.15 on 2022-09-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrift', '0006_auto_20220825_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_sold',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
