# Generated by Django 3.2.15 on 2022-09-16 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thrift', '0009_rename_name_item_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='picture',
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='thrift.item')),
            ],
        ),
    ]
