# Generated by Django 3.2.15 on 2022-09-30 23:27

from django.db import migrations, models
import django.db.models.deletion
import thrift.models


class Migration(migrations.Migration):

    dependencies = [
        ('thrift', '0010_auto_20220916_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=thrift.models.item_image_upload_handler),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_images', to='thrift.item'),
        ),
    ]
