# Generated by Django 3.2.15 on 2022-10-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrift', '0012_auto_20220930_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='ItemImage',
        ),
    ]
