# Generated by Django 3.2.15 on 2022-10-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thrift', '0013_auto_20221002_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_method',
            field=models.TextField(default='contact me at ...', max_length=256),
            preserve_default=False,
        ),
    ]
